[package]
name = "chatter"
version = "0.1.0"
entrypoint = "lib.typ"
authors = ["Sylvan Franklin"]
license = "MIT"
description = "Snappy Dialog"
repository = "https://github.com/sylvanfranklin/chatter"
categories = ["Template"]
keywords = ["English", "Homework", "Formatting", "Colorful"]
exclude = ["*.pdf"]
disciplines = ["writin'"]
